### ISSUE TITLE
Build failing when building tests

### ISSUE THREAD

**Issue by Fighter19** [nemerle/boomerang#61] opened 2016-05-18 23:13 UTC
```
[ 65%] Linking CXX executable ../../../out/TypeTest
CMakeFiles/TypeTest.dir/TypeTest.cpp.o: In function `TypeTest::testDataInterval()':
TypeTest.cpp:(.text+0x1ede): undefined reference to `bool QTest::qCompare<bool, int>(bool const&, int const&, char const*, char const*, char const*, int)'
TypeTest.cpp:(.text+0x1f68): undefined reference to `bool QTest::qCompare<bool, int>(bool const&, int const&, char const*, char const*, char const*, int)'
collect2: Error: ld returned 1
```

**Comment by ReDucTor** [comment] 2016-05-19 00:30
I need to do a pull-request again for my fork, should be fixed if I start a pull request with:
https://github.com/ReDucTor/boomerang/commit/7a3ae1e0d9f69479d0a381a7c4c442a75a84c412

**Comment by nemerle** [comment] 2016-05-19 11:23
@Fighter19   Which compiler ? Which Qt ?

**Comment by hakusdream** [comment] 2016-05-19 11:26
nemerle, it's the linker.

**Comment by nemerle** [comment] 2016-05-19 11:28
@hakusdream  The linker is reporting the error, but the missing reference might be caused by bad compiler-qt version: Qt compiled for vs2013 used with vs2015

**Comment by hakusdream** [comment] 2016-05-19 11:30
Mismatched header/binary.

**Comment by ReDucTor** [comment] 2016-05-19 11:42
Probably different versions of Qt, one which requires consistent types, the other did not.

It's just a template function that ensures types don't match for comparison and there is no implicit conversions happening, changing them to failing locations from ints to bools fixes the issue. (See earlier referenced commit)

**Comment by hakusdream** [comment] 2016-05-19 11:43
@ReDucTor See #62.

Rebase your commits, also.

**Comment by Fighter19** [comment] 2016-05-19 14:33
Actually this problem occured on ArchLinux with the current up-to-date libraries.

**Comment by hakusdream** [comment] 2016-05-19 19:28
I'll try on Ubuntu though Travis-CI.

**Closed** 2016-05-20 06:47 UTC
